import AppKit
import Combine

/// Recent clipboard text. Held in memory only — nothing you copy is
/// ever written to disk.
final class ClipboardStore: ObservableObject {
    struct Entry: Identifiable, Equatable {
        let id = UUID()
        let text: String

        var preview: String {
            text
                .trimmingCharacters(in: .whitespacesAndNewlines)
                .replacingOccurrences(of: "\n", with: " ")
        }
    }

    /// Types password managers and similar tools use to say "do not record this".
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword"
    ]

    @Published private(set) var entries: [Entry] = []

    let limit = 20

    private let pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var timer: Timer?

    init() {
        changeCount = pasteboard.changeCount
    }

    func start(interval: TimeInterval = 1) {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func copy(_ entry: Entry) {
        pasteboard.clearContents()
        pasteboard.setString(entry.text, forType: .string)
        changeCount = pasteboard.changeCount // our own write is not new history
        // Move it back to the front.
        entries.removeAll { $0 == entry }
        entries.insert(entry, at: 0)
    }

    func clear() {
        entries.removeAll()
    }

    private func poll() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.privateTypes) else { return }

        guard
            let text = pasteboard.string(forType: .string),
            !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        guard entries.first?.text != text else { return }
        entries.removeAll { $0.text == text }
        entries.insert(Entry(text: text), at: 0)
        if entries.count > limit { entries.removeLast(entries.count - limit) }
    }
}
